### ISSUE TITLE
gomlx shouldn't depend on deprecated Client APIs

### ISSUE THREAD

**Issue by cheshire** [gomlx/gomlx#52]
gomlx seems to call deprecated XLA Client APIs (e.g. https://github.com/gomlx/gomlx/blob/main/c/gomlx/computation.cpp#L743), but it should be using new PjRT ones. 

Lots of those API calls seem auto-generated, could we at least filter down to those which are actually used?

**Comment by janpfeifer** [comment]
hi George, yes, I've been postponing the PjRT ones because they lacked the type inference for the operations -- I need to figure out myself the shape of the output of the operations, while the XlaBuild provides that.

Can I keep using the XlaBuilder API -- for the type inference -- and then convert it to StableHLO and use PjRT to execute things ? What is the equivalent API in PjRT for tensors (OnDeviceBuffer and similar ?)

Sorry, when you mentioned "Lost of those API calls seem auto-generated", which API calls are you referring ? The Go ones in gomlx.xla where all manually written, and most are used -- except AOT and StableHLO, which I started a while back to try to get PjRT to work, but failed > year ago.

Btw, any recommend pointers for the PjRT API ? 

Thanks!!!

**Comment by janpfeifer** [comment]
I did find the base page (very poor on details and I didn't find any example) here:

https://github.com/openxla/xla/blob/main/xla/pjrt/c/README.md

The public design doc:

https://docs.google.com/document/d/1Qdptisz1tUPGn1qFAVgCV2omnfjN01zoQPwKLdlizas/edit

And some discussions here:

https://github.com/openxla/xla/issues/7038

But from the discussions, there are still some issues ... plus the BUILD rules are not clear ... that's one reason I hesitate investing too much time upfront and postpone as much as possible, till others braved the code "archeology".

The best documentation I get is asking Gemini to make sense of it for me 😄 

Am I missing something ?

**Comment by cheshire** [comment]
I think the first issue is that gomlx should stop using internal APIs, e.g. proto here https://github.com/gomlx/gomlx/blob/main/c/gomlx/aot_compile.cpp#L224-L226 is clearly internal (I'm still confused how did that even work with respect to visibility)

**Comment by cheshire** [comment]
> I did find the base page (very poor on details and I didn't find any example) here:

Could you ask in the PjRT/XLA repo for help on runtime docs?

**Comment by janpfeifer** [comment]
Yes, the AOT part was pointed out on a discussion > year ago by someone in XLA team. But it never fully worked. I'll drop that part for now, till I get PjRT working.

Any other internal parts I shouldn't use ? 

Is the Client API still working ? (I mean, it was in April when I last compiled the XLA binary)


About asking for help on PjRT/XLA, I thought that was the topic of https://github.com/openxla/xla/issues/7038, which is still open I believe. I did subscribe to it. But let me know if it helps opening another issue, I'd be happy to.

**Comment by cheshire** [comment]
> Yes, the AOT part was pointed out on a discussion > year ago by someone in XLA team. But it never fully worked. I'll drop that part for now, till I get PjRT working.

Yes please, the proto is an internal implementation detail of AOT. AOT itself works, but uses a different serialization now.

> Is the Client API still working ? (I mean, it was in April when I last compiled the XLA binary)

It still is, but we're actively trying to remove it.

**Comment by janpfeifer** [comment]
Thanks George.

The AOT part will be out in the next release of GoMLX -- hopefully tomorrow morning.

Changing to use PjRT will come next, but wrapping the PjRT C API in Go may take a while (weeks?). I'm still reading around, trying to figure out the details of how things work -- the lack of documentation makes it a pain😞

Btw, can you confirm the XlaBuilder will still work ? Can I use it to generate the HLO ? If not is there any other recommended way to get type/shape inference for the various ops ?

**Comment by cheshire** [comment]
XlaBuilder is not going away anytime soon. There's a plan to transition to
StableHLO fully, but that will take a while.

StableHLO however should support dynamic shapes and doing required shape
inference itself - maybe it's a question of finding the right APIs?

**Comment by janpfeifer** [comment]
> StableHLO however should support dynamic shapes and doing required shape
> inference itself - maybe it's a question of finding the right APIs?

Btw what do you mean by "finding the right APIs" ? Do you mean it's a question for the XLA team to find the right APIs to create them ?

**Comment by cheshire** [comment]
Nope, I've meant finding the right APIs for your project - as far as I understand JAX already builds dynamically shaped StableHLO for XLA and runs shape inference for it.

**Comment by janpfeifer** [comment]
Yes, but Jax does so in Python. My project is in Go.

Ideally, not everyone who uses PjRT would need to reimplement the shape inference ... the project that implements the ops usually implements the exptected output shape of them.  I'm sure it is implemented in PjRT somewhere (I assume it would return an error if the stablehlo declares the wrong inference type) ... it's just for some reason not exposed.

**Comment by cheshire** [comment]
> Yes, but Jax does so in Python. My project is in Go.

Surely MLIR C++ bindings are even better?

**Comment by janpfeifer** [comment]
What are the MLIR C++ bindings ? Better than what ? XlaBuilder ?

**Comment by janpfeifer** [comment]
I removed the offending C/C++ code you pointed out. I haven't yet created a new release because it will require recompiling XLA, and that is always lots of work (something always changes, and requires careful investigation of BUILD rules cross dependencies).

Let me know if that clears references to internal code for you. And if you have pointers to documentation on how to do AOT with XLA, they would be most welcome, I still wanted to support it :)

**Comment by cheshire** [comment]
Also CC @skye

**Comment by skye** [comment]
FYI PJRT does not cover generating any kind of HLO program. It's a generic compiler/runtime API, it doesn't have a strong opinion on the input that the compiler receives. So go ahead and keep using the XlaBuilder.

**Comment by janpfeifer** [comment]
Thanks for the confirmation Skye.

Now, from my other question in https://github.com/openxla/xla/issues/13733, after generating the StableHLO with XlaBuilder, I can get away with compilation/execution using exclusively the PJRT C API, correct ? That's a viable way forward ?

**Comment by skye** [comment]
Yup that's right (once you create the correct inputs to PJRT_Client_Compile or PJRT_Compile)

**Comment by janpfeifer** [comment]
Just a heads up: with the new v0.11.0 release, GoMLX now depends on [gopjrt](https://github.com/gomlx/gopjrt) and has no other C/C++ dependencies.

[gopjrt](https://github.com/gomlx/gopjrt) itself depends solely on the XlaBuilder (to build the MLO program) and PJRT C API (to compile and execute it).

Closing the issue.

@cheshire thanks again for the report and help!! Let me know if you know of any issues.

**Comment by cheshire** [comment]
Thanks!
